/**
 * 静态数据
 */

export const Production= [

    {
        title:'通用标题',
        icon:'./assets/img/icon_file_default.png',
        content:'标题位于正中间，左边是返回，右边是菜单样式',
        subtitle:'',
        updateTime:'2020-11-16',
        cate:'page',//类型-图标介绍
        path:'zztable',//案由
    },
    {
        title:'文件选择',
        icon:'./assets/img/icon_file_default.png',
        content:'从本地选择文件，上传到服务器，根据文件不同类型有对应图标展示。',
        subtitle:'',
        updateTime:'2020-11-16',
        cate:'page',//类型-图标介绍
        path:'filechoose',//案由
    },
    {
        title:'二级菜单',
        icon:'./assets/img/icon_file_default.png',
        content:'适用于二级菜单，且二级条目中数据在0-20左右，多了的话显示效果也不好，可以单选也可以多选。',
        subtitle:'',
        updateTime:'2020-11-16',
        cate:'page',//类型-图标介绍
        path:'zztable',//案由
    },
    {
        title:'首行首列固定表格',
        icon:'./assets/img/icon_file_default.png',
        content:'表格的首行，在上滑的时候会固定住，左右滑动的时候，首列也能固定住。',
        subtitle:'',
        updateTime:'2020-11-16',
        cate:'page',//类型-图标介绍
        path:'zztable',//案由
    },
    {
        title:'通用列表',
        icon:'./assets/img/icon_file_default.png',
        content:'下拉刷新，上拉加载更多等',
        subtitle:'',
        updateTime:'2020-11-16',
        cate:'page',//类型-图标介绍
        path:'listview',//案由
    },
]